---
- name: Konfigurasi Router SMKN1 MGL
  hosts: mls
  gather_facts: false

  module_defaults:
    cisco.ios.ios_config:
      diff_against: running

  tasks:
    - name: Coba ios sistem
      cisco.ios.ios_system:
        hostname: "{{ hostname }}"
        domain_name: "{{ domain }}"
