---
- name: Konfigurasi Router SMKN1 MGL
  hosts: routers
  gather_facts: false

  module_defaults:
    cisco.ios.ios_config:
      diff_against: running

  tasks:
    - name: 1.a. Konfigurasi hostname & domain
      cisco.ios.ios_system:
        hostname: "{{ hostname }}"
        domain_name: "{{ domain }}"

    - name: 2. Deskripsi dan Aktifasi Interfaces
      cisco.ios.ios_interfaces:
        config:
          - name: "{{ item.name }}"
            description: "{{ item.desc }}"
            enabled: "{{ item.enabled }}"
        state: merged
      loop: "{{ interfaces }}"

    - name: 3. Konfiguasi IP
      cisco.ios.ios_l3_interfaces:
        config:
          - name: "{{ item.name }}"
            ipv4:
              - address: "{{ item.ip }}"
        state: merged
      loop: "{{ interfaces }}"

    - name: 4. DHCP excluded address
      cisco.ios.ios_config:
        lines: "ip dhcp excluded-address {{ item }}"
      loop: "{{ dhcp_excluded }}"

    - name: 5. DHCP Pools
      cisco.ios.ios_config:
        parents: "ip dhcp pool {{ item.name }}"
        lines:
          - network {{ item.network }}
          - default-router {{ item.default_router }}
      loop: "{{ dhcp_pools }}"

    - name: 6.a. Static routers
      cisco.ios.ios_static_routes:
        config:
          - address_families:
              - afi: ipv4
                routes:
                  - dest: "{{ item.dest }}"
                    next_hops:
                      - forward_router_address: "{{ item.next_hop }}"
      loop: "{{ static_routes | default([]) }}"
      when: static_routes is defined

    - name: 6.b. OSPF Router
      cisco.ios.ios_ospfv2:
        config:
          processes:
            - router_id: "{{ ospf.router_id }}"
              process_id: 1
              network: "{{ ospf.networks }}"

#    - name: 7. Simpan running ke startup
#      cisco.ios.ios_command:
#        commands: "write memory"
