---
- name: Konfigurasi Multilayer Switch SMKN1 Magelang
  hosts: mls
  gather_facts: false

# modul untuk --diff jika diperukan
  module_defaults:
    cisco.ios.ios_config:
      diff_against: running # dibandingkan dengan running-config

  tasks:
# -----KONFIGURASI DASAR
    - name: 1. Konfigurasi hostname & domain
      cisco.ios.ios_system:
        hostname: "{{ hostname }}"
        domain_name: "{{ domain }}"
      tags: manual, dasar

# -----PEMBUATAN VLAN
    - name: 2. Konfigurasi VLAN
      cisco.ios.ios_vlans:
        config:
          - vlan_id: "{{ item.id }}"
            name: "{{ item.name }}"
            state: active
        state: merged
      loop: "{{ vlans }}" # looping variabel vlans
      tags: otomatis, vlan

# -----KONFIGURASI SVI untuk VLAN
    - name: 3. Konfigurasi Deskripsi dan kondisi SVI
      cisco.ios.ios_interfaces:
        config:
          - name: "{{ item.name }}"
            description: "{{ item.desc }}"
            enabled: true
        state: merged
      loop: "{{ svis }}" # looping variabel svis
      tags: otomatis, interfaces

    - name: 4. Konfigurasi IP SVI (Gateway VLAN)
      cisco.ios.ios_l3_interfaces:
        config:
          - name: "{{ item.name }}"
            ipv4:
              - address: "{{ item.ip }}"
        state: merged
      loop: "{{ svis }}"
      tags: otomatis, interfaces, vlan

    - name: 5. IP Helper-address DHCP
      cisco.ios.ios_config:
        parents: "interface {{ item.name }}"
        lines: "ip helper-address {{ item.ip_helper }}"
      loop: "{{ svis }}"
      when: item.ip_helper is defined # menjalankan task ini apabila ip_helper ada pada variabel svis
      tags: otomatis, dhcp, interfaces

# -----KONFIGURASI INTERFACES MLS --> ROUTER
    - name: 6. Konfigurasi Mode port L3 MLS, deskripsi, dan aktifasi
      cisco.ios.ios_interfaces:
        config:
          - name: "{{ item.name }}"
            mode: "layer3"
            description: "{{ item.desc }}"
            enabled: true
        state: merged
      loop: "{{ routed_interfaces }}" # looping pada variabel routed_interfaces
      tags: manual, interfaces

    - name: 7. Konfigurasi IP L3 MLS
      cisco.ios.ios_l3_interfaces:
        config:
          - name: "{{ item.name }}"
            ipv4:
              - address: "{{ item.ip }}"
        state: merged
      loop: "{{ routed_interfaces }}"
      tags: manual, interfaces

# -----KONFIGURASI TRUNK
    - name: 8. Deskripsi interfaces trunk
      cisco.ios.ios_interfaces:
        config:
          - name: "{{ item.name }}"
            description: "{{ item.desc }}"
            enabled: true
        state: merged
      loop: "{{ trunk_interfaces }}"  # Looping pada variabel trunk_interfaces
      tags: otomatis, vlan, interfaces, trunk

    - name: 9. Konfigurasi interfaces trunk
      cisco.ios.ios_config:
        parents: "interface {{ item.name }}"
        lines:
          - switchport trunk encapsulation dot1q
          - switchport mode trunk
      loop: "{{ trunk_interfaces }}"
      tags: otomatis, vlan, interfaces, trunk

# -----KONFIGURASI UNUSED PORT
    - name: 10. Set mode access pada unused port
      cisco.ios.ios_config:
        parents: "interface {{ item }}"
        lines: " switchport mode access"
      loop: "{{ shutdown_ports }}"  # looping pada variabel shutdown_ports
      tags: otomatis, unused, interfaces

    - name: 11. Shutdown unused port
      cisco.ios.ios_interfaces:
        config:
          - name: "{{ item }}"
            enabled: false # mematikan port
        state: merged
      loop: "{{ shutdown_ports }}"
      tags: otomatis, unused

# -----KONFIGURASI OSPF
    - name: 12. Konfigurasi OSPF
      cisco.ios.ios_ospfv2:
        config:
          processes:
            - process_id: "{{ ospf.process }}"
              router_id: "{{ ospf.router_id }}"
              network: "{{ ospf.networks }}"
        state: merged
      tags: manual, otomatis, routing, ospf

# -----KONFIGURASI ACL
    - name: 13. Pembuatan ACL Vlan10_in
      cisco.ios.ios_config:
        parents: "ip access-list {{ item.type }} {{ item.name }}" # Masuk ke parent ip access-list
# Looping for untuk setiap nilai destination pada variabel akses
# Menggunakan pipeline " | " agar perintah mudah dibaca
        lines: |
          {% for dest in item.destination %}
           deny    ip {{ item.source }} host {{ dest }}
          {% endfor %}
          permit ip any any
      loop: "{{ akses }}" # Looping pada variabel akses
      tags: otomatis, acl, keamanan

    - name: 14. Penerapan ACL
      cisco.ios.ios_acl_interfaces:
        config:
          - name: "{{ item.apply }}"
            access_groups:
              - afi: ipv4
                acls:
                  - name: "{{ item.name }}"
                    direction: "{{ item.direction }}"
        state: merged
      loop: "{{ akses }}"
      tags: otomatis, acl, keamanan

#    - name: 7. Simpan running ke startup
#      cisco.ios.ios_command:
#        commands: "write memory"
#      tags: simpan
