---
- name: Konfigurasi Switch Access SMKN1 Magelang
  hosts: switches
  gather_facts: false

# Module untuk --diff jika dibutuhkan
  module_defaults:
    cisco.ios.ios_config:
      diff_against: running

  tasks:
# -----KONFIGURASI DASAR
    - name: 1. Konfigurasi hostname & domain
      cisco.ios.ios_system:
        hostname: "{{ hostname }}"
        domain_name: "{{ domain }}"
      tags: otomatis, dasar

# -----KONFIGURASI VLAN
    - name: 2. Konfigurasi Vlan
      cisco.ios.ios_vlans:
        config:
          - vlan_id: "{{ item.id }}"
            name: "{{ item.name }}"
            state: active
        state: merged
      loop: "{{ vlans }}"
      tags: otomatis, vlan

# -----KONFIGURASI INTERFACES VLAN MANAJEMEN
    - name: 3. Deskripsi dan Aktifkan Vlan1
      cisco.ios.ios_interfaces:
        config:
          - name: "Vlan1"
            description: "Manajemen"
            enabled: true
        state: merged
      tags: manual, interfaces, vlan

    - name: 4. Konfigurasi IP Manajemen
      cisco.ios.ios_l3_interfaces:
        config:
          - name: "Vlan1"
            ipv4:
              - address: "{{ vlan1_ip }}"
        state: merged
      tags: otomatis, interfaces, vlan

# -----KONFIGURASI DEFAULT GATEWAY
    - name: 5. Konfigurasi default-gateway u/ Manajemen
      cisco.ios.ios_config:
        lines:
          - "ip default-gateway {{ default_gateway }}"
      tags: manual, interaces

# -----KONFIGURASI TRUNK
    - name: 6. Deskripsi dan enable trunk interaces
      cisco.ios.ios_interfaces:
        config:
          - name: "{{ item.name }}"
            description: "{{ item.desc }}"
            enabled: true
        state: merged
      loop: "{{ trunk_interfaces }}"
      tags: otomatis, interfaces, trunk, vlan

    - name: 7. Konfigurasi Encapsulation Trunk dan port mode
      cisco.ios.ios_config:
        parents: "interface {{ item.name }}"
        lines:
          - switchport trunk encapsulation dot1q
          - switchport mode trunk
      loop: "{{ trunk_interfaces }}"
      tags: otomatis, trunk, vlan, interfaces

# -----KONFIGURASI ACCESS PORT VLAN & PORT SECURITY
    - name: 8. Konfigurasi access port (VLAN, deskripsi, port-security)
      cisco.ios.ios_config:
        parents: "interface {{ item.name }}"
        lines:
          - switchport access vlan {{ item.vlan }}
          - switchport mode access
          - switchport port-security
          - switchport port-security violation restrict
          - switchport port-security mac-address sticky
      loop: "{{ access_ports }}"
      tags: otomatis, interfaces, vlan, keamanan

    - name: 8.b. Enable & Deskripsi Interfaces Access
      cisco.ios.ios_interfaces:
        config:
          - name: "{{ item.name }}"
            description: "{{ item.desc }}"
            enabled: true
        state: merged
      loop: "{{ access_ports }}"
      tags: otomatis, interfaces, vlan

# -----KONFIGURASI UNUSED PORT
    - name: 9. Access Mode pada unused port
      cisco.ios.ios_config:
        parents: "interface {{ item }}"
        lines: "switchport mode access"
      loop: "{{ shutdown_ports }}"
      tags: otomatis, unused

    - name: 10. Shutdown unused port
      cisco.ios.ios_interfaces:
        config:
          - name: "{{ item }}"
            enabled: false
        state: merged
      loop: "{{ shutdown_ports }}"
      tags: otomatis, unused

#    - name: 11. Simpan running ke startup
#      cisco.ios.ios_command:
#        commands: "write memory"
#      tags: simpan
