---
- name: Konfigurasi Multilayer Switch SMKN1 Magelang
  hosts: mls
  gather_facts: false

  tasks:

    - name: 13. Pembuatan ACL Vlan10_in
      cisco.ios.ios_config:
        parents: "ip access-list {{ item.type }} {{ item.name }}"
        lines: |
          {% for dest in item.destination %}
           deny    ip {{ item.source }} host {{ dest }}
          {% endfor %}
          permit ip any any
      loop: "{{ akses }}"

    - name: 14. Penerapan ACL
      cisco.ios.ios_acl_interfaces:
        config:
          - name: "{{ item.apply }}"
            access_groups:
              - afi: ipv4
                acls:
                  - name: "{{ item.name }}"
                    direction: in
        state: merged
      loop: "{{ akses }}"
