---

# MEMANGGIL SETIAP PLAYBOOK MENJADI SATU PLAYBOOK site.yml
- name: Backup Konfigurasi
  ansible.builtin.import_playbook: /home/mmrfai/netauto-smkn1/playbook/backup_config.yml

- name: Konfigurasi Router
  ansible.builtin.import_playbook: /home/mmrfai/netauto-smkn1/playbook/konfigurasi_router.yml # HARUS FQDN

- name: Konfigurasi MLS
  ansible.builtin.import_playbook: /home/mmrfai/netauto-smkn1/playbook/konfigurasi_mls.yml

- name: Konfigurasi Switch
  ansible.builtin.import_playbook: /home/mmrfai/netauto-smkn1/playbook/konfigurasi_switch.yml
