---
hostname: M_SER
domain: smkn1mgl.sch.id

vlans:
  - { id: 10, name: "lab" }
  - { id: 20, name: "guru" }
  - { id: 30, name: "server" }

svis:
  - { name: "Vlan1", ip: "192.168.10.1/26", desc: "manajemen ansible" }
  - { name: "Vlan10", ip: "172.16.10.1/24", desc: "lab", ip_helper: "10.10.10.13" }
  - { name: "Vlan20", ip: "172.20.10.1/24", desc: "guru", ip_helper: "10.10.10.13" }
  - { name: "Vlan30", ip: "192.168.30.1/27", desc: "server" }

routed_interfaces:
  - { name: "Ethernet0/0", desc: "R_SER", ip: "10.10.10.14/30", enabled: true }

trunk_interfaces:
  - { name: "Ethernet1/0", desc: "S_SER" }
  - { name: "Ethernet1/1", desc: "S_GURU" }
  - { name: "Ethernet1/2", desc: "S_LAB" }

shutdown_ports: [
  "Ethernet0/1", "Ethernet0/2", "Ethernet0/3",
  "Ethernet1/3", "Ethernet2/0", "Ethernet2/1",
  "Ethernet2/2", "Ethernet2/3", "Ethernet3/0",
  "Ethernet3/1", "Ethernet3/2", "Ethernet3/3"
]

ospf:
  process: 1
  router_id: "11.11.11.11"
  networks:
    - { address: "10.10.10.12", wildcard_bits: "0.0.0.3", area: 0 }
    - { address: "192.168.10.0", wildcard_bits: "0.0.0.63", area: 0}
    - { address: "172.16.10.0", wildcard_bits: "0.0.0.255", area: 0}
    - { address: "172.20.10.0", wildcard_bits: "0.0.0.255", area: 0}
    - { address: "192.168.30.0", wildcard_bits: "0.0.0.31", area: 0}

acls:
  - name: "Vlan10_in"
    acl_type: "extended"
    aces:
      - { sequence: 10, grant: "deny", protocol: "ip", source: { address: "172.16.10.0", wildcard_bits: "0.0.0.255" }, destination: { address: "192.168.30.10", wildcard_bits: "0.0.0.0" } }
      - { sequence: 20, grant: "deny", protocol: "ip",source: { address: "172.16.10.0", wildcard_bits: "0.0.0.255" }, destination: { address: "192.168.30.5", wildcard_bits: "0.0.0.0" } }
      - { sequence: 30, grant: "permit", protocol: "ip",source: { any: true }, destination: { any: true } }
    apply_to: "Vlan10"
    direction: "in"
