---
hostname: R_BMO
domain: smkn1mgl.sch.id

interfaces:
  - { name: "Ethernet0/1", desc: "R_SER", ip: "10.10.10.6/30", enabled: true }
  - { name: "Ethernet0/2", desc: "R_EIL", ip: "10.10.10.10/30", enabled: true }
  - { name: "Ethernet0/3", desc: "M_BMO", ip: "10.10.10.21/30", enabled: true }

dhcp_excluded: [172.16.30.1, 172.20.30.1]

dhcp_pools:
  - { name: "lab-BMO", network: "172.16.30.0 255.255.255.0", default_router: "172.16.30.1" }
  - { name: "guru-BMO", network: "172.20.30.0 255.255.255.0", default_router: "172.20.30.1" }

ospf:
  process: 1
  router_id: 3.3.3.3
  networks:
    - { address: "10.10.10.4", wildcard_bits: "0.0.0.3", area: 0 }
    - { address: "10.10.10.8", wildcard_bits: "0.0.0.3", area: 0 }
    - { address: "10.10.10.20", wildcard_bits: "0.0.0.3", area: 0 }
