hostname: "S_BA"
domain: smkn1mgl.sch.id

vlans:
  - { id: 10, name: "lab" }
  - { id: 20, name: "guru" }

trunk_interfaces:
  - { name: "Ethernet0/0", desc: "M_BMO"}

access_ports:
  - { name: "Ethernet1/0", vlan: 20, desc: "guru" }
  - { name: "Ethernet1/1", vlan: 20, desc: "guru" }
  - { name: "Ethernet1/2", vlan: 20, desc: "guru" }
  - { name: "Ethernet1/3", vlan: 20, desc: "guru" }
  - { name: "Ethernet2/0", vlan: 10, desc: "lab" }
  - { name: "Ethernet2/1", vlan: 10, desc: "lab" }
  - { name: "Ethernet2/2", vlan: 10, desc: "lab" }
  - { name: "Ethernet2/3", vlan: 10, desc: "lab" }

shutdown_ports: [
  "Ethernet0/1", "Ethernet0/2", "Ethernet0/3",
  "Ethernet3/0", "Ethernet3/1", "Ethernet3/2", "Ethernet3/3"
]

default_gateway: "192.168.10.129"
vlan1_ip: "192.168.10.131/26"
