# Identitas Perangkat
hostname: S_SER
domain: smkn1mgl.sch.id

# Vlan yang dibuat
vlans:
  - { id: 30, name: "server" }

# Interface Trunk
trunk_interfaces:
  - { name: "Ethernet0/0", desc: "M_SER" }

# Interface Access VLAN
access_ports:
  - { name: "Ethernet1/0", vlan: 30, desc: "server" }
  - { name: "Ethernet1/1", vlan: 30, desc: "server" }
  - { name: "Ethernet1/2", vlan: 30, desc: "server" }

# Interfaces yang tidak digunakan
shutdown_ports: [
  "Ethernet0/1", "Ethernet0/2", "Ethernet0/3",
  "Ethernet1/3", "Ethernet2/0", "Ethernet2/1",
  "Ethernet2/2", "Ethernet2/3", "Ethernet3/0",
  "Ethernet3/1", "Ethernet3/2", "Ethernet3/3"
]

# Interface manajemen
default_gateway: "192.168.10.1"
vlan1_ip: "192.168.10.10/26"
