[routers]
R_SER ansible_host=10.10.10.1
R_EIL ansible_host=10.10.10.2
R_BMO ansible_host=10.10.10.6

[mls]
M_SER ansible_host=10.10.10.14
M_EIL ansible_host=10.10.10.18
M_BMO ansible_host=10.10.10.22

[switches]
S_SER ansible_host=192.168.10.10
S_GURU ansible_host=192.168.10.11
S_LAB ansible_host=192.168.10.12
S_EL ansible_host=192.168.10.71
S_IN ansible_host=192.168.10.72
S_LIS ansible_host=192.168.10.73
S_BA ansible_host=192.168.10.131
S_ME ansible_host=192.168.10.132
S_OT ansible_host=192.168.10.133

[Blok_SER]
R_SER
M_SER
S_SER
S_GURU
S_LAB

[Blok_EIL]
R_EIL
M_EIL
S_EL
S_IN
S_LIS

[Blok_BMO]
R_BMO
M_BMO
S_BA
S_ME
S_OT

#variabel global untuk semua perangkat
[all:vars]
#cara ansible konek ke perangkat
ansible_connection=ansible.netcommon.network_cli
ansible_network_os=cisco.ios.ios

#kredensial ssh
ansible_user=admin
ansible_become=yes
ansible_become_method=enable

