[routers]
R_SER ansible_host=10.10.10.1
R_EIL_MOD ansible_host=10.10.10.2
R_BMO_MOD ansible_host=10.10.10.6
R_ALT ansible_host=10.10.10.26 # SAMBUNG KE R_BMO dan R_EIL

[mls]
M_SER ansible_host=10.10.10.14
M_EIL ansible_host=10.10.10.18
M_BMO ansible_host=10.10.10.22
M_ALT ansible_host=10.10.10.34 # Penambahan MLS

[switches]
S_SER ansible_host=192.168.10.10
S_GURU ansible_host=192.168.10.11
S_LAB ansible_host=192.168.10.12
S_EL ansible_host=192.168.10.71
S_IN ansible_host=192.168.10.72
S_LIS ansible_host=192.168.10.73
S_BA ansible_host=192.168.10.131
S_ME ansible_host=192.168.10.132
S_OT ansible_host=192.168.10.133
S_AG ansible_host=192.168.10.201 # Penambahan Switch
S_PL ansible_host=192.168.10.202 # Penambahan Switch
S_PT ansible_host=192.168.10.203 # Penambahan Switch

[BLOK_SER]
R_SER
M_SER
S_SER
S_GURU
S_LAB

[BLOK_EIL]
R_EIL_MOD
M_EIL
S_EL
S_IN
S_LIS

[BLOK_BMO]
R_BMO_MOD
M_BMO
S_BA
S_ME
S_OT

# AGROTEKNO, PELAYARAN, PERTAMBANGAN
[BLOK_ALT]
R_ALT
M_ALT
S_AG
S_PL
S_PT

# 11 baris ditambah pada inventory

#variabel global untuk semua perangkat
[all:vars]
#cara ansible konek ke perangkat
ansible_connection=ansible.netcommon.network_cli
ansible_network_os=cisco.ios.ios

#kredensial ssh
ansible_user=admin
ansible_become=yes
ansible_become_method=enable

