[routers]
#R-SER ansible_host=10.10.10.1
R-EIL ansible_host=10.10.10.2
#R-BMO ansible_host=10.10.10.6

[mls]
#M-SER ansible_host=10.10.10.14
M-EIL ansible_host=10.10.10.18
#M-BMO ansible_host=10.10.10.22

[switches]
#S-SER ansible_host=192.168.10.10
#S-GURU ansible_host=192.168.10.11
#S-LAB ansible_host=192.168.10.12
S-EL ansible_host=192.168.10.71
S-IN ansible_host=192.168.10.72
S-LIS ansible_host=192.168.10.73
#S-BA ansible_host=192.168.10.131
#S-MA ansible_host=192.168.10.132
#S-OT ansible_host=192.168.10.133

#variabel global untuk semua perangkat
[all:vars]
#cara ansible konek ke perangkat
ansible_connection=ansible.netcommon.network_cli
ansible_network_os=cisco.ios.ios

#kredensial ssh
ansible_user=admin
ansible_become=yes
ansible_become_method=enable